services:
  - type: web
    name: clara-homework-server
    env: python
    plan: starter
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn homework_server_rag:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: MAX_UPLOAD_FILES
        value: "10"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: RATE_LIMIT_WINDOW_SECONDS
        value: "60"
      - key: ALLOWED_ORIGINS
        sync: false